server:
  port: 8023
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_chicken?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: root
    password: root
  jpa:
    show-sql: true